const userRole = {
  USER: "USER",
  ADMIN: "ADMIN",
};

const validErrorName = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_REQUEST: "INVALID_REQUEST",
  API_NOT_FOUND: "API_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  NOT_FOUND: "NOT_FOUND",
  NO_DATA_PROVIDED: "NO_DATA_PROVIDED",
  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  ACCESS_DENIED: "ACCESS_DENIED",
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  PHONE_NUMBER_EXISTS: "PHONE_NUMBER_EXISTS",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
  NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  CAR_ALREADY_BOOKED: "CAR_ALREADY_BOOKED",
};

const emailPhone = {
  PHONE: "PHONE",
  EMAIL: "EMAIL",
};

const status = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
};
const tripType = ["LOCAL", "ROUND_TRIP", "AIRPORT"];

const tripTypes = {
  LOCAL: "LOCAL",
  ROUND_TRIP: "ROUND_TRIP",
  AIRPORT: "AIRPORT",
};
const paymentToBe = {
  PAY_NOW: "PAY_NOW",
  PAY_LATER: "PAY_LATER",
};

module.exports = {
  userRole,
  validErrorName,
  emailPhone,
  status,
  tripType,
  tripTypes,
  paymentToBe,
};
