const userRole = {
  USER: "USER",
  ADMIN: "ADMIN",
};

const validErrorName = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  INVALID_REQUEST: "INVALID_REQUEST",
  API_NOT_FOUND: "API_NOT_FOUND",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  UNEXPECTED_ERROR: "UNEXPECTED_ERROR",
  NOT_FOUND: "NOT_FOUND",
  NO_DATA_PROVIDED: "NO_DATA_PROVIDED",
  VERIFICATION_FAILED: "VERIFICATION_FAILED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  ACCESS_DENIED: "ACCESS_DENIED",
  EMPLOYER_ALREADY_EXISTS: "EMPLOYER_ALREADY_EXISTS",
  SEEKER_ALREADY_EXISTS: "SEEKER_ALREADY_EXISTS",
  UNAUTHORIZED_USER: "UNAUTHORIZED_USER",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  PHONE_NUMBER_EXISTS: "PHONE_NUMBER_EXISTS",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  BLACKLISTED_TOKEN: "BLACKLISTED_TOKEN",
  NO_TOKEN_PROVIDED: "NO_TOKEN_PROVIDED",
  ROLE_MISMATCH: "ROLE_MISMATCH",
  SUBSCRIPTION_REQUIRED: "SUBSCRIPTION_REQUIRED",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  HIRING_MANAGER_NOT_ASSIGNED: "HIRING_MANAGER_NOT_ASSIGNED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INVALID_PASSWORD: "INVALID_PASSWORD",
};

const emailPhone = {
  PHONE: "PHONE",
  EMAIL: "EMAIL",
};

const status = {
  ACTIVE: "ACTIVE",
  BLOCKED: "BLOCKED",
};

module.exports = {
  userRole,
  validErrorName,
  emailPhone,
  status,
};
